config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :destroy] do
    member do
      get :followings
      get :followers
      get :likings
      get :likes
    end
    
=begin
    collection do
      get :search
    end
=end

  end

  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  
  ############################################################
  #お気に入り用
=begin
  resources :users, only: [:create, :destroy] do
    member do
      get :likings
      get :likes
    end
  end

  resources :favorites, only: [:create, :destroy]
=end
  ############################################################
  
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 255 }
  
  ####################################################################
  has_many :favorites
  ####################################################################

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = 'メッセージを投稿しました。'
      redirect_to root_url
    else
      @microposts = current_user.feed_microposts.order('created_at DESC').page(params[:page])
      flash.now[:danger] = 'メッセージの投稿に失敗しました。'
      render 'toppages/index'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = 'メッセージを削除しました。'
    redirect_back(fallback_location: root_path)
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    unless @micropost
      redirect_to root_url
    end
  end
end

#@micropost = Micropost.find(params[:id])
#redirect_to root_url if @micropost.user != current_user

app/views/microposts/_microposts.html.erb
<ul class="media-list">
  <%= render 'microposts/user_profile_show_micropost', micropost_show:microposts %>
  <%= paginate microposts %>
</ul>

app/views/microposts/_user_profile_show_micropost.html.erb
<% micropost_show.each do |micropost| %>
  <li class="media">
    <div class="media-left">
      <img class="media-object img-rounded" src="<%= gravatar_url(micropost.user, options = { size: 50 }) %>" alt="">
    </div>
    <div class="media-body">
      <div>
        <%= link_to micropost.user.name, user_path(micropost.user) %> <span class="text-muted">posted at <%= micropost.created_at %></span>
      </div>
      <div>
        <p><%= micropost.content %></p>
      </div>
      
      <%# 削除ボタン %>
      <div>
        <% if current_user == micropost.user %>
          <%= link_to "Delete", micropost, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-xs' %>
        <% end %>
      </div>
    
      <%# お気に入りボタン %>
      <div>
        
        <%# if current_user == micropost.user (自分自身もお気に入り可能)%>
        
          <% unless current_user.liking?(micropost) %>
            <%= link_to "Favorite", favorites_path(micropost_id: micropost.id), method: :post, class: 'btn btn-success btn-xs' %>
        
          <% else %>
            <% favorite = current_user.favorites.find_by(micropost_id: micropost.id) %>
            <%= link_to "UnFavorite", favorite_path(favorite,micropost_id: micropost.id), method: :delete, class: 'btn btn-warning btn-xs' %>
          <% end %>
          
        <%# end %>
      </div>
      
    </div>
  </li>
<% end %>

app/views/microposts/create.html.erb
<h1>Microposts#create</h1>
<p>Find me in app/views/microposts/create.html.erb</p>

app/views/microposts/destroy.html.erb
<h1>Microposts#destroy</h1>
<p>Find me in app/views/microposts/destroy.html.erb</p>